site_name: "WEB-labs documentation"

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'

nav:
  - Home: index.md
  - Lab №1:
      - Task 1: task1.md
      - Task 2: task2.md
      - Task 3: task3.md
      - Task 4: task4.md
      - Task 5: task5.md
  - Lab №2:
      - Lab task + main functional: task2.md
